name: Check Coding Norms
on: [push]

jobs:
  run_norms:
    runs-on: ubuntu-latest
    name: Check Coding Norms
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: plotioda
    
    - name: Check Coding Norms
      run: |
        cd $GITHUB_WORKSPACE/plotioda
        pycodestyle -v --config ./.pycodestyle .
    
