name: Run all CI tests
on: [push, pull_request]

jobs:
  run_all_tests:
    runs-on: ubuntu-latest
    name: Build IODA, EMCPy, and plotioda, and run all tests.
    container: jcsda/docker-gnu-openmpi-dev
    steps:

    - name: Build IODA
      run: |
        cd $GITHUB_WORKSPACE
        mkdir ioda-bundle
        cd ioda-bundle
        wget https://github.com/CoryMartin-NOAA/JEDI-T2O/blob/main/bundles/ioda/CMakeLists.txt
        cd ..
        mkdir build
        cd build
        ecbuild ../ioda-bundle
        make -j2
        ctest
      
